---
- name: Stop Firewalld (for docker)
  service: name=firewalld state=stopped enabled=no

- name: Install ntp
  yum: name=ntp state=present

- name: Enable and start ntp
  service: name=ntpd state=started enabled=yes

- name: Install kubernetes
  yum: name=kubernetes state=present

- name: changing kubernetes config
  lineinfile:
    dest: "/etc/kubernetes/apiserver"
    regexp: "{{ item.key }}="
    line: "{{ item.key }}={{ item.value }}"
  with_items:
    - { key: 'KUBE_API_ADDRESS', value: '"--address=0.0.0.0"' }
    - { key: 'KUBE_API_PORT', value: '"--port=8080"' }
    - { key: 'KUBELET_PORT', value: '"--kubelet_port=10250"' }
    - { key: 'KUBE_ETCD_SERVERS', value: '"--etcd_servers=http://127.0.0.1:2379"' }
    - { key: 'KUBE_SERVICE_ADDRESSES', value: '"--service-cluster-ip-range=10.254.0.0/16"' }
    - { key: 'KUBE_ADMISSION_CONTROL', value: '"--admission_control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ResourceQuota"' }
    - { key: 'KUBE_API_ARGS', value: '""' }

- name: start kubernetes services
  service: name={{ item }} state=started enabled=yes
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
