# https://www.digitalocean.com/community/tutorials/how-to-install-nginx-on-ubuntu-16-04
# https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-16-04
# https://www.htpcguides.com/secure-nginx-reverse-proxy-with-lets-encrypt-on-ubuntu-16-04-lts/
---
- name: Install nginx
  become: yes
  apt: name=nginx state=present

- name: Add ufw firewall rules for SSL
  become: yes
  ufw: rule=allow name="Nginx Full"

- name: Remove default from sites-enabled
  become: yes
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: restart-nginx

- name: Add reverse to sites-available
  become: yes
  template: dest=/etc/nginx/sites-available/reverse src=reverse.j2
  notify: restart-nginx

- name: Add resevese to sites-enabled
  become: yes
  file: src=/etc/nginx/sites-available/reverse dest=/etc/nginx/sites-enabled/reverse state=link
  notify: restart-nginx

- name: Add certbot repository
  become: yes
  apt_repository: repo="ppa:certbot/certbot"

- name: Install python-certbot-nginx
  become: yes
  apt: name=python-certbot-nginx state=present

- name: Start and enable nginx
  become: yes
  service: name=nginx state=started enabled=yes

#sudo certbot run -d winter.varokas.com --nginx -m "varokas@panusuwan.com" --agree-tos --redirect -n

